"""Export a diff-cam trajectory to RS274/NGC G-code.

A diff-cam trajectory is an ``(T, 3)`` array of tool-tip positions in the unit
cube ``[0, 1]^3``. We emit standard linear-move G-code (the same canonical moves
LinuxCNC's interpreter produces: ``STRAIGHT_TRAVERSE`` = G0, ``STRAIGHT_FEED`` =
G1):

    G21            ; millimetres
    G90            ; absolute distance mode
    G61            ; exact-stop path control (stop at every waypoint)
    G0 X.. Y.. Z.. ; rapid to the first point
    F<feed>
    G1 X.. Y.. Z.. ; feed move to each subsequent point
    ...
    M2             ; program end

Coordinates are scaled from the unit cube to millimetres via
``MachineConfig.workspace_mm`` so the parser can invert the mapping exactly.
"""

import numpy as np

from .config import MachineConfig


def _fmt(value: float, precision: int) -> str:
    """Format one coordinate value, trimming trailing zeros but keeping it
    unambiguous (``0`` stays ``0``)."""
    s = f"{value:.{precision}f}"
    if "." in s:
        s = s.rstrip("0").rstrip(".")
    return s if s not in ("", "-0") else "0"


def _axis_words(point_mm, precision: int) -> str:
    x, y, z = point_mm
    return (
        f"X{_fmt(x, precision)} "
        f"Y{_fmt(y, precision)} "
        f"Z{_fmt(z, precision)}"
    )


def trajectory_to_gcode(positions, config: MachineConfig = MachineConfig()) -> str:
    """Convert an ``(T, 3)`` unit-cube trajectory to a G-code program string.

    The first point is reached with a rapid (G0); every subsequent point is a
    cutting feed move (G1). Exact-stop mode (G61) means the planner that later
    re-reads this program will pass through every waypoint.
    """
    positions = np.asarray(positions, dtype=np.float64)
    if positions.ndim != 2 or positions.shape[1] != 3:
        raise ValueError(f"positions must be (T, 3); got {positions.shape}")
    if len(positions) == 0:
        raise ValueError("positions is empty")

    pts_mm = positions * config.workspace_mm
    p = config.precision

    lines = [
        "(Generated by diff-cam cam.gcode_export)",
        config.units_code,        # G21 / G20
        "G90",                    # absolute distance mode
        "G61",                    # exact-stop path control
    ]

    # Rapid to the first waypoint.
    lines.append(f"G0 {_axis_words(pts_mm[0], p)}")

    if len(pts_mm) > 1:
        lines.append(f"F{_fmt(config.feed, p)}")
        for pt in pts_mm[1:]:
            lines.append(f"G1 {_axis_words(pt, p)}")

    lines.append("M2")
    return "\n".join(lines) + "\n"


def save_gcode(positions, path, config: MachineConfig = MachineConfig()) -> str:
    """Write the G-code for ``positions`` to ``path`` and return the program text."""
    text = trajectory_to_gcode(positions, config)
    with open(path, "w") as f:
        f.write(text)
    return text
