"""Configurable G-code post-processors.

A *post-processor* turns an ``(T, 3)`` unit-cube trajectory into a machine-
specific G-code program. Two posts ship today:

* :class:`RS274Post` (``"rs274"``) -- the generic LinuxCNC-style program
  (``G21``/``G90``/``G61`` + ``G0``/``G1`` + ``M2``). This is the faithful,
  approach-free output used for round-trip fidelity checks.
* :class:`HaasPost` (``"haas"``) -- a Fanuc-style program ready to load on a
  Haas Mini Mill: program number, safety block, tool change with length offset,
  spindle + coolant, an explicit clearance/plunge approach, and ``M30``.

Register additional machines by adding a :class:`PostProcessor` subclass to
:data:`POSTS`; everything else (``trajectory_to_gcode``, the export script, the
CLI ``--post`` flag) picks them up automatically.
"""

import numpy as np

from .config import MachineConfig
from .units import mm_to_inch, mm_per_min_to_ipm


# ---------------------------------------------------------------------------
# Output-unit helpers
# ---------------------------------------------------------------------------
# Internally everything is millimetres. The post declares G21 (mm) or G20
# (inch); when inch is requested the coordinate and feed VALUES must be
# converted too -- otherwise the program declares inches but emits mm numbers.
# These convert just prior to G-code emission (cf. cam.units).
def _len_out(value_mm, config: MachineConfig):
    """Length in mm -> the configured output units (scalar or array)."""
    return mm_to_inch(value_mm) if config.units == "inch" else value_mm


def _feed_out(feed_mm_per_min: float, config: MachineConfig) -> float:
    """Feed in mm/min -> the configured output units (mm/min or in/min)."""
    return mm_per_min_to_ipm(feed_mm_per_min) if config.units == "inch" else feed_mm_per_min


# ---------------------------------------------------------------------------
# Formatting helpers (shared by all posts)
# ---------------------------------------------------------------------------
def _fmt(value: float, precision: int) -> str:
    """Format one coordinate value, trimming trailing zeros but keeping it
    unambiguous (``0`` stays ``0``)."""
    s = f"{value:.{precision}f}"
    if "." in s:
        s = s.rstrip("0").rstrip(".")
    return s if s not in ("", "-0") else "0"


def _axis_words(point_mm, precision: int) -> str:
    x, y, z = point_mm
    return (
        f"X{_fmt(x, precision)} "
        f"Y{_fmt(y, precision)} "
        f"Z{_fmt(z, precision)}"
    )


# ---------------------------------------------------------------------------
# Post-processor base + implementations
# ---------------------------------------------------------------------------
class PostProcessor:
    """Base class. Subclasses implement :meth:`program`."""

    name = "base"

    def program(self, positions, config: MachineConfig) -> str:
        raise NotImplementedError

    @staticmethod
    def _validate(positions):
        positions = np.asarray(positions, dtype=np.float64)
        if positions.ndim != 2 or positions.shape[1] != 3:
            raise ValueError(f"positions must be (T, 3); got {positions.shape}")
        if len(positions) == 0:
            raise ValueError("positions is empty")
        return positions


class RS274Post(PostProcessor):
    """Generic RS274/NGC output (the original diff-cam exporter).

    The first point is reached with a rapid (G0); every subsequent point is a
    cutting feed move (G1). Exact-stop mode (G61) means a planner re-reading
    this program passes through every waypoint, so the round trip
    ``trajectory -> G-code -> trajectory`` reproduces the original path.
    """

    name = "rs274"

    def program(self, positions, config: MachineConfig = MachineConfig()) -> str:
        positions = self._validate(positions)
        # Normalized stock coords [0,1] -> work-coordinate-system mm (top-centre
        # G54), then mm -> output units.
        pts_out = _len_out(config.to_wcs(positions), config)
        feed_out = _feed_out(config.feed, config)
        p = config.precision

        lines = [
            "(Generated by diff-cam cam.posts.RS274Post)",
            config.units_code,        # G21 / G20
            "G90",                    # absolute distance mode
            "G61",                    # exact-stop path control
        ]

        # Rapid to the first waypoint.
        lines.append(f"G0 {_axis_words(pts_out[0], p)}")

        if len(pts_out) > 1:
            lines.append(f"F{_fmt(feed_out, p)}")
            for pt in pts_out[1:]:
                lines.append(f"G1 {_axis_words(pt, p)}")

        lines.append("M2")
        return "\n".join(lines) + "\n"


class HaasPost(PostProcessor):
    """Fanuc-style program for a Haas Mini Mill.

    Structure::

        %
        O00001 (DIFFCAM)
        G17 G40 G49 G80 G90      ; safety block
        G21                      ; units
        G54                      ; work offset
        T1 M06                   ; tool change
        G43 H1 Z<safe>           ; tool length offset, rapid to clearance
        S5000 M03                ; spindle on (CW)
        M08                      ; flood coolant on
        G00 X.. Y..              ; rapid above the first point
        G01 Z.. F<plunge>        ; plunge to the first depth
        F<feed>
        G01 X.. Y.. Z..          ; cutting moves through the trajectory
        ...
        G00 Z<safe>              ; retract
        M09                      ; coolant off
        M05                      ; spindle off
        G53 G00 Z0.              ; home Z in machine coordinates
        M30                      ; program end + rewind
        %
    """

    name = "haas"

    def program(self, positions, config: MachineConfig = MachineConfig()) -> str:
        positions = self._validate(positions)
        # Normalized stock coords [0,1] -> work-coordinate-system mm (top-centre
        # G54), then mm -> output units.
        pts_out = _len_out(config.to_wcs(positions), config)
        feed_out = _feed_out(config.feed, config)
        plunge_out = _feed_out(config.plunge_feed, config)
        p = config.precision
        safe = _fmt(_len_out(config.safe_z_mm, config), p)

        lines = [
            "%",
            f"O{config.program_number:05d} ({config.program_name})",
            "(Post: Haas Mini Mill -- generated by diff-cam cam.posts.HaasPost)",
            "G17 G40 G49 G80 G90",                 # safety block
            config.units_code,                     # G21 / G20
            config.work_offset,                    # G54
            f"T{config.tool_number} M06",          # tool change
            f"G43 H{config.h_register} Z{safe}",   # length offset, rapid to clearance
            f"S{_fmt(config.spindle_rpm, 0)} M03", # spindle CW
        ]

        # Program the work offset (G54..G59) to the stock origin in machine
        # coords, so the program is self-contained: coords below are relative to
        # the stock's top-centre and the controller knows where that sits. The
        # operator need only confirm the machine zero. Pxx selects the fixture
        # offset register: G54->P1, G55->P2, ...
        if config.stock_origin_in is not None:
            ox, oy, oz = _len_out(config.stock_origin_vec, config)
            p_reg = int(config.work_offset[1:]) - 53  # "G54" -> 1
            idx = lines.index(config.work_offset) + 1
            lines.insert(
                idx,
                f"G10 L2 P{p_reg} X{_fmt(ox, p)} Y{_fmt(oy, p)} Z{_fmt(oz, p)}",
            )

        if config.coolant:
            lines.append("M08")

        # Approach: rapid above the first XY, then plunge to the first depth.
        x0, y0, z0 = pts_out[0]
        lines.append(f"G00 X{_fmt(x0, p)} Y{_fmt(y0, p)}")
        lines.append(f"G01 Z{_fmt(z0, p)} F{_fmt(plunge_out, p)}")

        # Cutting moves through the rest of the trajectory.
        if len(pts_out) > 1:
            lines.append(f"F{_fmt(feed_out, p)}")
            for pt in pts_out[1:]:
                lines.append(f"G01 {_axis_words(pt, p)}")

        # Retract / shutdown.
        lines.append(f"G00 Z{safe}")
        if config.coolant:
            lines.append("M09")
        lines.append("M05")
        lines.append("G53 G00 Z0.")                # home Z (machine coords)
        lines.append("M30")
        lines.append("%")
        return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------
POSTS = {
    RS274Post.name: RS274Post,
    HaasPost.name: HaasPost,
}


def get_post(name: str = "rs274") -> PostProcessor:
    """Return an instance of the named post-processor."""
    try:
        return POSTS[name.lower()]()
    except KeyError:
        raise ValueError(
            f"unknown post '{name}'; available posts: {sorted(POSTS)}"
        )
